<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Forgot your password</name>
   <tag></tag>
   <elementGuidId>3d549385-7bef-4e9b-ba61-4dd055298a80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cred_forgot_password_link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cred_forgot_password_link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://passwordreset.microsoftonline.com:443/?ru=https%3a%2f%2flogin.microsoftonline.com%2fgecopvautaadb2cqvca001.onmicrosoft.com%2freprocess%3fctx%3drQIIAbWRv4vTYBzGm6Q9z-PAQ5cuwg3ioLR5k7S9XrFgsbXXmB8XmzSkgpimb9o35keTvk0v8R-Qm8SxDsohKDc6ibgL53KjON54IIiT4GK7ON_i8H2W58MDz_e5RTFFpnZjMGBNFnJmwSrDnULJBmahWoWgsDzGHnK2xdil6OrGlnf2-c71_NG9wyfvf7z-UxQWxM0RtIJJbM6waQ4HrBXGlgkAUwx8D1lRMA1sXLQC75h4NMZ4Mq3RtBuMkF_85wa-i3y4YmgM6Yul0cGSGLP0SiM4nXwkiFOCOCSzDOC4BZmDfkHrviGJYzLfdkK9H1e9eTMyhAg0B3G621Pq9e_kFbmxCllJEKEU_iJz4QxGyYJ6RXSxieF-FExghBGc1mHCq11NQTLiS4LOpIIuzU0dYMsTK33HmouqkshtBRvpUyAiAERHTAS9kxqOhiVPciS1lchNJe3rWrmD5qjXclsdJ0B9VQMGq6WS08Di0pO6AEjpfSSoriupIyy3HyLDM1hZ592-yo87PvhAXfDlJ9Qm9Ezkbi9b-Gj4jSLOqGuhyd0ducHAdOGBBd0Vd5olzrObgKqtr29sZfKZ7czvLHGUW6799fH5y-YM8G_VZ7tf3vmZkxxtQJyG3dgwwgNOrYDkgbQ33WnZvbIYa9Feeptv7SudijRP1Ua9VGNerK39XCOfX8p8uvw_9_8L0&amp;mkt=en-US&amp;hosted=0&amp;device_platform=Windows+10&amp;nca=1&amp;domain_hint=gecopvautaadb2cqvca001.onmicrosoft.com&amp;username=qa3%40globalexcel.com</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forgot your password?</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cta_error_message_text&quot;)/div[@id=&quot;recover_container&quot;]/p[2]/a[@id=&quot;cred_forgot_password_link&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cred_forgot_password_link']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recover_container']/p[2]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Forgot your password?')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('We don', &quot;'&quot;, 't recognize this user ID or password')])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We have a new sign-in experience!'])[1]/following::a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type the email address of the account you want to sign in with.'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in to {0}'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Forgot your password?']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://passwordreset.microsoftonline.com:443/?ru=https%3a%2f%2flogin.microsoftonline.com%2fgecopvautaadb2cqvca001.onmicrosoft.com%2freprocess%3fctx%3drQIIAbWRv4vTYBzGm6Q9z-PAQ5cuwg3ioLR5k7S9XrFgsbXXmB8XmzSkgpimb9o35keTvk0v8R-Qm8SxDsohKDc6ibgL53KjON54IIiT4GK7ON_i8H2W58MDz_e5RTFFpnZjMGBNFnJmwSrDnULJBmahWoWgsDzGHnK2xdil6OrGlnf2-c71_NG9wyfvf7z-UxQWxM0RtIJJbM6waQ4HrBXGlgkAUwx8D1lRMA1sXLQC75h4NMZ4Mq3RtBuMkF_85wa-i3y4YmgM6Yul0cGSGLP0SiM4nXwkiFOCOCSzDOC4BZmDfkHrviGJYzLfdkK9H1e9eTMyhAg0B3G621Pq9e_kFbmxCllJEKEU_iJz4QxGyYJ6RXSxieF-FExghBGc1mHCq11NQTLiS4LOpIIuzU0dYMsTK33HmouqkshtBRvpUyAiAERHTAS9kxqOhiVPciS1lchNJe3rWrmD5qjXclsdJ0B9VQMGq6WS08Di0pO6AEjpfSSoriupIyy3HyLDM1hZ592-yo87PvhAXfDlJ9Qm9Ezkbi9b-Gj4jSLOqGuhyd0ducHAdOGBBd0Vd5olzrObgKqtr29sZfKZ7czvLHGUW6799fH5y-YM8G_VZ7tf3vmZkxxtQJyG3dgwwgNOrYDkgbQ33WnZvbIYa9Feeptv7SudijRP1Ua9VGNerK39XCOfX8p8uvw_9_8L0&amp;mkt=en-US&amp;hosted=0&amp;device_platform=Windows+10&amp;nca=1&amp;domain_hint=gecopvautaadb2cqvca001.onmicrosoft.com&amp;username=qa3%40globalexcel.com')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/a</value>
   </webElementXpaths>
</WebElementEntity>
