<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Forgot your password</name>
   <tag></tag>
   <elementGuidId>d81a274a-8576-4bc1-bfa6-bc6e8597cd7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cred_forgot_password_link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cred_forgot_password_link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://passwordreset.microsoftonline.com:443/?ru=https%3a%2f%2flogin.microsoftonline.com%2fgecopvautaadb2cqvca001.onmicrosoft.com%2freprocess%3fctx%3drQIIAbWRv2_TQBzF_SMppapEoQPd6IAYkBKf7ZRUkSIIdRJixXHbOAkO0-VySS6yfbFz-eWNAQkhgVgJC2LMRsUASPwDnTqiDiBYkJiACZiIF-YuDO8t34-e9L7vuign5czVVkuBClZhAu3gdCLVATCxu4tBYim501Y7SO6kgktrG5evXPzx-_ODvbe-9ez008c_c_5aFyM6GMMRg7DdUpA_RhAAOUk9l6CADmmHJRF1F_y9HmODYUaSHNolXvLflXoO8XDESAxLZ0uT6JLoKVLkAR4O3vD8Cc8_EmIyUNW5EMdeolZ9IfALYauOgv1yCEk6l9frASzWu74xzWWzp8IFMxeFREYDEuKfQtwf4WA2F5_zVQYZ3g_oAAeM4GEWz3SrWjsgJtFT5YYclhuVCWwAhlzjRrNY6Dfd_I7dzzMjrIWVGQC2UlpypZmt2KyiFXp2PzeJ1CzqbolMSD3v5Et9SgwLpUwNAUOzmR0asrkHQEXr9cpWVzHcGjO0Zq9iHRJDOXSXWWrJA0fiGV9-LK5jFxJne9nCI-0PIv9F3PSheqvr0BZ08BRhJ-JOYvy32DoQM6uraxvcFrfN_YrxL-PLtcnm0QI8-aq_4m6-fvz-Pnccl-7oJLQqt7URJUPUat81KZi26wcpf1RIy8Qxx02r3KgOlUkaZJWM_HRl5fuK8PAc9-78_9z_Lw2&amp;mkt=en-US&amp;hosted=0&amp;device_platform=Windows+10&amp;nca=1&amp;domain_hint=gecopvautaadb2cqvca001.onmicrosoft.com&amp;username=qa3%40globalexcel.com</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forgot your password?</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cta_error_message_text&quot;)/div[@id=&quot;recover_container&quot;]/p[2]/a[@id=&quot;cred_forgot_password_link&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cred_forgot_password_link']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recover_container']/p[2]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Forgot your password?')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('We don', &quot;'&quot;, 't recognize this user ID or password')])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We have a new sign-in experience!'])[1]/following::a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type the email address of the account you want to sign in with.'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in to {0}'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Forgot your password?']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://passwordreset.microsoftonline.com:443/?ru=https%3a%2f%2flogin.microsoftonline.com%2fgecopvautaadb2cqvca001.onmicrosoft.com%2freprocess%3fctx%3drQIIAbWRv2_TQBzF_SMppapEoQPd6IAYkBKf7ZRUkSIIdRJixXHbOAkO0-VySS6yfbFz-eWNAQkhgVgJC2LMRsUASPwDnTqiDiBYkJiACZiIF-YuDO8t34-e9L7vuign5czVVkuBClZhAu3gdCLVATCxu4tBYim501Y7SO6kgktrG5evXPzx-_ODvbe-9ez008c_c_5aFyM6GMMRg7DdUpA_RhAAOUk9l6CADmmHJRF1F_y9HmODYUaSHNolXvLflXoO8XDESAxLZ0uT6JLoKVLkAR4O3vD8Cc8_EmIyUNW5EMdeolZ9IfALYauOgv1yCEk6l9frASzWu74xzWWzp8IFMxeFREYDEuKfQtwf4WA2F5_zVQYZ3g_oAAeM4GEWz3SrWjsgJtFT5YYclhuVCWwAhlzjRrNY6Dfd_I7dzzMjrIWVGQC2UlpypZmt2KyiFXp2PzeJ1CzqbolMSD3v5Et9SgwLpUwNAUOzmR0asrkHQEXr9cpWVzHcGjO0Zq9iHRJDOXSXWWrJA0fiGV9-LK5jFxJne9nCI-0PIv9F3PSheqvr0BZ08BRhJ-JOYvy32DoQM6uraxvcFrfN_YrxL-PLtcnm0QI8-aq_4m6-fvz-Pnccl-7oJLQqt7URJUPUat81KZi26wcpf1RIy8Qxx02r3KgOlUkaZJWM_HRl5fuK8PAc9-78_9z_Lw2&amp;mkt=en-US&amp;hosted=0&amp;device_platform=Windows+10&amp;nca=1&amp;domain_hint=gecopvautaadb2cqvca001.onmicrosoft.com&amp;username=qa3%40globalexcel.com')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/a</value>
   </webElementXpaths>
</WebElementEntity>
