<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Forgot your password</name>
   <tag></tag>
   <elementGuidId>377d7702-e859-4401-a166-1227a5495229</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cred_forgot_password_link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cred_forgot_password_link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://passwordreset.microsoftonline.com:443/?ru=https%3a%2f%2flogin.microsoftonline.com%2fgecopvautaadb2cqvca001.onmicrosoft.com%2freprocess%3fctx%3drQIIAbVRPWzTUBiM7SSUqqgVLF2QOiAGqsR_aRIiRZA0P6TEdk2cuA7Ti_PiPNc_if3axBaICQlVDMypQIgxIxNCYmSphFTEgliQGEBiqpg64izMXRi-W767k-7uFsWm2cKNXo8DHORBSt-CuVRmwIBUPg-ZVHTsoM8PdHaQ8a4ur_36cnb08fvLytP7V46vS5_AjLhpQN0dHYIDDEC_x-njQx0wDJt2HRvpnuu7A5zWXXtOPBxiPPILNG25BnLS_76uYyEHLjg0hvTF3Gg3Ygw5eoEe9EfvCOKUII7IOMvw_IxMQCfVbr0miTm5vq1mO2V5SvPIuH1v33A6dasbTIrFb-SqVFqYLMD1UAj_kInxAfSCGXVMtDDAcNdzR9DDCPpFGOworbaMJLSTaaps2FTFCVAZrNtCVlT6tmZrvKYIWAhLQXebYQRF45qKZYqmhkXT2Ooq5X1JrQ2lihw00AR1qla1YbpIrOiBoMqhYAtYqrcnQivS1oVIa2TEUI601YlYkadaOBxq3APUcJi31AUrP6FWoA2QtRGlcFD_K0X8oK6NAX_XsNwesOBUh9aCdxonfsdXGKqwtLS8FluPbcTO48SbRLT2k9XHc7j3ofbqZ_7O5-ePYicJWhEAt1lrN_ypn83B3O5eiZO4qAE8ZjdNTzLFctbpsPWg1MgX2QL7Ipk8S5LPLsXeX_6f-_8F0&amp;mkt=en-US&amp;hosted=0&amp;device_platform=Windows+10&amp;nca=1&amp;domain_hint=gecopvautaadb2cqvca001.onmicrosoft.com&amp;username=qa3%40globalexcel.com</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forgot your password?</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cta_error_message_text&quot;)/div[@id=&quot;recover_container&quot;]/p[2]/a[@id=&quot;cred_forgot_password_link&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cred_forgot_password_link']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recover_container']/p[2]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Forgot your password?')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('We don', &quot;'&quot;, 't recognize this user ID or password')])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We have a new sign-in experience!'])[1]/following::a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type the email address of the account you want to sign in with.'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in to {0}'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Forgot your password?']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://passwordreset.microsoftonline.com:443/?ru=https%3a%2f%2flogin.microsoftonline.com%2fgecopvautaadb2cqvca001.onmicrosoft.com%2freprocess%3fctx%3drQIIAbVRPWzTUBiM7SSUqqgVLF2QOiAGqsR_aRIiRZA0P6TEdk2cuA7Ti_PiPNc_if3axBaICQlVDMypQIgxIxNCYmSphFTEgliQGEBiqpg64izMXRi-W767k-7uFsWm2cKNXo8DHORBSt-CuVRmwIBUPg-ZVHTsoM8PdHaQ8a4ur_36cnb08fvLytP7V46vS5_AjLhpQN0dHYIDDEC_x-njQx0wDJt2HRvpnuu7A5zWXXtOPBxiPPILNG25BnLS_76uYyEHLjg0hvTF3Gg3Ygw5eoEe9EfvCOKUII7IOMvw_IxMQCfVbr0miTm5vq1mO2V5SvPIuH1v33A6dasbTIrFb-SqVFqYLMD1UAj_kInxAfSCGXVMtDDAcNdzR9DDCPpFGOworbaMJLSTaaps2FTFCVAZrNtCVlT6tmZrvKYIWAhLQXebYQRF45qKZYqmhkXT2Ooq5X1JrQ2lihw00AR1qla1YbpIrOiBoMqhYAtYqrcnQivS1oVIa2TEUI601YlYkadaOBxq3APUcJi31AUrP6FWoA2QtRGlcFD_K0X8oK6NAX_XsNwesOBUh9aCdxonfsdXGKqwtLS8FluPbcTO48SbRLT2k9XHc7j3ofbqZ_7O5-ePYicJWhEAt1lrN_ypn83B3O5eiZO4qAE8ZjdNTzLFctbpsPWg1MgX2QL7Ipk8S5LPLsXeX_6f-_8F0&amp;mkt=en-US&amp;hosted=0&amp;device_platform=Windows+10&amp;nca=1&amp;domain_hint=gecopvautaadb2cqvca001.onmicrosoft.com&amp;username=qa3%40globalexcel.com')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/a</value>
   </webElementXpaths>
</WebElementEntity>
