<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Forgot your password</name>
   <tag></tag>
   <elementGuidId>289a6b83-e834-4ccc-889f-77a8b9a92581</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cred_forgot_password_link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cred_forgot_password_link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://passwordreset.microsoftonline.com:443/?ru=https%3a%2f%2flogin.microsoftonline.com%2fgecopvautaadb2cqvca001.onmicrosoft.com%2freprocess%3fctx%3drQIIAbVRO2zTUBSN7aQ_VaKCpWMFiAEp8XOchCRSJAJJqqSxXWO7xmFynJfkpbaf7bx8HMSKAIEEC0O6IBZQRiZgZ2injhEjIwNCnRiJF-YuDPdI995zj3Tuuc1wKa54s91Om2nIm0krC-8kM11gJvN5CJKr4rodvmtx3UxwdWvn-bK2gNrb2puL02-vPrz8OKdu9aCFvbE5IqbZaactf2yZAHAp7DrICvAQd0nKws6CetQnxBsWWdbGPeSm_m2xayMXRhyWQPZyaixeMfppNsIADr3PFHVOUS_oOAd4fk4noJvUlHc0taB3D2oaOj4cZ-oDv-6L5YKLy3quVyp9p69I5UgkAhygGbygE_4IBuGcOaEUYhJ4GGAPBgTBYQmGDVXRZCShRqapc7OmLk5MHRDLEXJSpToVdZkT9mUizqyJdB-A1SzbVI9nLdUg0r6WFRxjJlZkIDoCX0cTdFS1q_UBRi21Fxq6zEu6TFqqNRERAKuei26NQZkYupER01paUOuh6Bhh3QWfmEu-_IzZho6J7L2VCxd1lgz1g7nmm_zdno3bpg2nFrQj3nmc-hnfBkxxY2NrJ7Yb24v9iVPvE6u0b3z51UDrT4ST5eb108dPY2cJVqndE0LffigcHGmNloerjqQUxEpe8fpQy8r-6EE4tIc5vTDFpWyRe7229nuNfrYe-7r5P_P_Cw2&amp;mkt=en-US&amp;hosted=0&amp;device_platform=Windows+10&amp;nca=1&amp;domain_hint=gecopvautaadb2cqvca001.onmicrosoft.com&amp;username=qa3%40globalexcel.com</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forgot your password?</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cta_error_message_text&quot;)/div[@id=&quot;recover_container&quot;]/p[2]/a[@id=&quot;cred_forgot_password_link&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cred_forgot_password_link']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recover_container']/p[2]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Forgot your password?')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('We don', &quot;'&quot;, 't recognize this user ID or password')])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We have a new sign-in experience!'])[1]/following::a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type the email address of the account you want to sign in with.'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in to {0}'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Forgot your password?']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://passwordreset.microsoftonline.com:443/?ru=https%3a%2f%2flogin.microsoftonline.com%2fgecopvautaadb2cqvca001.onmicrosoft.com%2freprocess%3fctx%3drQIIAbVRO2zTUBSN7aQ_VaKCpWMFiAEp8XOchCRSJAJJqqSxXWO7xmFynJfkpbaf7bx8HMSKAIEEC0O6IBZQRiZgZ2injhEjIwNCnRiJF-YuDPdI995zj3Tuuc1wKa54s91Om2nIm0krC-8kM11gJvN5CJKr4rodvmtx3UxwdWvn-bK2gNrb2puL02-vPrz8OKdu9aCFvbE5IqbZaactf2yZAHAp7DrICvAQd0nKws6CetQnxBsWWdbGPeSm_m2xayMXRhyWQPZyaixeMfppNsIADr3PFHVOUS_oOAd4fk4noJvUlHc0taB3D2oaOj4cZ-oDv-6L5YKLy3quVyp9p69I5UgkAhygGbygE_4IBuGcOaEUYhJ4GGAPBgTBYQmGDVXRZCShRqapc7OmLk5MHRDLEXJSpToVdZkT9mUizqyJdB-A1SzbVI9nLdUg0r6WFRxjJlZkIDoCX0cTdFS1q_UBRi21Fxq6zEu6TFqqNRERAKuei26NQZkYupER01paUOuh6Bhh3QWfmEu-_IzZho6J7L2VCxd1lgz1g7nmm_zdno3bpg2nFrQj3nmc-hnfBkxxY2NrJ7Yb24v9iVPvE6u0b3z51UDrT4ST5eb108dPY2cJVqndE0LffigcHGmNloerjqQUxEpe8fpQy8r-6EE4tIc5vTDFpWyRe7229nuNfrYe-7r5P_P_Cw2&amp;mkt=en-US&amp;hosted=0&amp;device_platform=Windows+10&amp;nca=1&amp;domain_hint=gecopvautaadb2cqvca001.onmicrosoft.com&amp;username=qa3%40globalexcel.com')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/a</value>
   </webElementXpaths>
</WebElementEntity>
