<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Bandazi  Bicumbi  Bihembe  Bugaragar_989edf</name>
   <tag></tag>
   <elementGuidId>4df9c678-355e-425d-af86-cb43565b71ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='City']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>City</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>City</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Bandazi  Bicumbi  Bihembe  Bugaragara  Bugarura  Bugesera  Bulega  Bulimba  Bumbogo  Butale  Butamwa  Gahengele  Gasaba  Gasagara  Gashinia  Gashora  Gasura  Gatete  Gikomero  Gikondo  Gikoro  Gishute  Gisodzi  Gitambi  Gitovu  Gitshatsha  Gitsimba  Gitsuba  Isenga  Janjagiro  Jari  Kabuga  Kacyiru  Kagasa  Kalembule  Kanombe  Kanyoni  Kanzenze  Karama  Karambo  Karizinge  Karotshyo  Katshuriro  Kayanga  Kayenzi  Kayovu  Kibagabaga  Kibungu  Kigali  Kigali  Kigali  Kigali  Kigali  Kigali  Kigali  Kigali  Kigali  Kigali  Kigali  Kigali  Kigali  Kigarama  Kimironko  Kindonye  Kinzuzi  Kirambo  Kisigiro  Kivuba  Kiyanza  Kukabira  Kukana  Kulisha  Leberu  Mabuye  Magina  Mamfu  Masoro  Mayange  Mbogo  Mibuba  Mont Kigali  Mpanga  Mpira  Mugambazi  Muko  Mukuyu  Mulinja  Murambi  Murara  Musasa  Musumule  Mutambiko  Muvumu  Mwendo  Mwishe  Mwite  Mwiviro  Myariro  Ndera  Ngange  Ngenda  Ngeruka  Ngiryi  Nkunzuzu  Ntarabana  Ntebe  Ntonde  Nyakabongo  Nyamweru  Nyanza  Nyarugenge  Nyarurama  Nzangwa  Remera  Rimwe  Rubona  Rubungo  Rugaragara  Rugenge  Ruhanga  Ruhanya  Rukura  Runyinya  Rushashi  Rusiga  Rutonde  Rutondwe  Rutongo  Rwamiko  Rwani  Rwankuba  Shenga  Shyorongi  Tanda  Tare  Tshyugaro  キガリ  吉佳利  키갈리 </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;City&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='City']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contactsModal']/div/div/div[2]/div/div[8]/div/div/div/div[2]/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City:'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address:'])[2]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country:'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State:'])[1]/preceding::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div[2]/select</value>
   </webElementXpaths>
</WebElementEntity>
