<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Forgot your password</name>
   <tag></tag>
   <elementGuidId>5ebcd860-1167-4496-8018-a23e86f56beb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cred_forgot_password_link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cred_forgot_password_link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://passwordreset.microsoftonline.com:443/?ru=https%3a%2f%2flogin.microsoftonline.com%2fgecopvautaadb2cqvca001.onmicrosoft.com%2freprocess%3fctx%3drQIIAbWRP4zSYBjGaQt4kosSXW68wTiYQL-Pwh0hkmhsbYq0PaRQDqdSPqB_Pygf_zrqYgxGZ24xDg43GRPNRTcXk5vOzaiTg4OTfxbHo4vzLQ7vs7zP-0ve57nGwCwsXel0ckYOcUbGLKDdTL4HjEyxiEBmPbDX5Xom7OWDS6n08kHl4PGbL8K75Z9fr19MUivqah-ZeDg1JsQwup2cOZqaBgAwi33PMgM8xj2SNbF3SN0bEDIcl1jWxX3Lz_7bYt-1fBR5WILYs9FYvHYMcmykARoPjyjqhKIe0XEIOG5FJ5CfadSf0dQhvaVAD3PszqI1mBe4IR_O9N2OWCuXP9MX1ZsRJBIcWCH6TSdGExQsVswBVScGQXsBHqKAWGhcRouKVm_ULNWq5Ks6DKu6MjN0QExP3lG1pi2LTU_mJSLrMlRuAdDmB4Oq5oC23ScqL8wVTZ63dZlTNSkvWTOrKbiCZGNLsV1PthtQ1hqkbTuL6FYR225V63MRT9H3w31d4BRdAGv2TPLBK-aMkR8zm8gzLHd7_YVvdT8x1Dfm8sjgbvRd3DFcNDeRG_lO4tSP-CZgShsbqXRsK7Yd-xunnifWbV9IX__43v_Av_y6PHry_X7sOMHu1YWWI7NiRWxNa6x5p-kg8W4TClKR57vh7VBxgJqTKn7BGZeLJfg0mfyZpB-ei709_z_7PwU1&amp;mkt=en-US&amp;hosted=0&amp;device_platform=Windows+10&amp;nca=1&amp;domain_hint=gecopvautaadb2cqvca001.onmicrosoft.com&amp;username=qa3%40globalexcel.com</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forgot your password?</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cta_error_message_text&quot;)/div[@id=&quot;recover_container&quot;]/p[2]/a[@id=&quot;cred_forgot_password_link&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cred_forgot_password_link']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recover_container']/p[2]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Forgot your password?')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('We don', &quot;'&quot;, 't recognize this user ID or password')])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We have a new sign-in experience!'])[1]/following::a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type the email address of the account you want to sign in with.'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in to {0}'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Forgot your password?']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://passwordreset.microsoftonline.com:443/?ru=https%3a%2f%2flogin.microsoftonline.com%2fgecopvautaadb2cqvca001.onmicrosoft.com%2freprocess%3fctx%3drQIIAbWRP4zSYBjGaQt4kosSXW68wTiYQL-Pwh0hkmhsbYq0PaRQDqdSPqB_Pygf_zrqYgxGZ24xDg43GRPNRTcXk5vOzaiTg4OTfxbHo4vzLQ7vs7zP-0ve57nGwCwsXel0ckYOcUbGLKDdTL4HjEyxiEBmPbDX5Xom7OWDS6n08kHl4PGbL8K75Z9fr19MUivqah-ZeDg1JsQwup2cOZqaBgAwi33PMgM8xj2SNbF3SN0bEDIcl1jWxX3Lz_7bYt-1fBR5WILYs9FYvHYMcmykARoPjyjqhKIe0XEIOG5FJ5CfadSf0dQhvaVAD3PszqI1mBe4IR_O9N2OWCuXP9MX1ZsRJBIcWCH6TSdGExQsVswBVScGQXsBHqKAWGhcRouKVm_ULNWq5Ks6DKu6MjN0QExP3lG1pi2LTU_mJSLrMlRuAdDmB4Oq5oC23ScqL8wVTZ63dZlTNSkvWTOrKbiCZGNLsV1PthtQ1hqkbTuL6FYR225V63MRT9H3w31d4BRdAGv2TPLBK-aMkR8zm8gzLHd7_YVvdT8x1Dfm8sjgbvRd3DFcNDeRG_lO4tSP-CZgShsbqXRsK7Yd-xunnifWbV9IX__43v_Av_y6PHry_X7sOMHu1YWWI7NiRWxNa6x5p-kg8W4TClKR57vh7VBxgJqTKn7BGZeLJfg0mfyZpB-ei709_z_7PwU1&amp;mkt=en-US&amp;hosted=0&amp;device_platform=Windows+10&amp;nca=1&amp;domain_hint=gecopvautaadb2cqvca001.onmicrosoft.com&amp;username=qa3%40globalexcel.com')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/a</value>
   </webElementXpaths>
</WebElementEntity>
