<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__fas fa-2x fa-phone-slash</name>
   <tag></tag>
   <elementGuidId>5a535dc6-e953-456b-bcd5-804e525f2b71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainDiv']/div/div/div/div/div/div[3]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-2x fa-phone-slash</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainDiv&quot;)/div[@class=&quot;container-fluid mainTriageContainer mw-100&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-3 mainTriageMenuLeft&quot;]/div[@class=&quot;menu-patient&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-1 h-100 my-auto&quot;]/a[1]/i[@class=&quot;fas fa-2x fa-phone-slash&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainDiv']/div/div/div/div/div/div[3]/a/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/i</value>
   </webElementXpaths>
</WebElementEntity>
