<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Forgot your password</name>
   <tag></tag>
   <elementGuidId>0ccb086c-0f29-4340-a93b-e729a75698f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cred_forgot_password_link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cred_forgot_password_link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://passwordreset.microsoftonline.com:443/?ru=https%3a%2f%2flogin.microsoftonline.com%2fgecopvautaadb2cqvca001.onmicrosoft.com%2freprocess%3fctx%3drQIIAbWRPYsTURiFMzNJXJeFXRRhsXEFsRCSufMRd40ETDYhJObObDYzCYlscTO5k9xkZm5mcvM1v0C0sdRso5YLKliJP2Gx2FIEGxvFSsRCO5PGehuL9zTvw4Fzzi1BSkrpG-22jGSsoISVwrsJ1QYosbeHQWJ5kt1RbEuy1eDS-tbhq_SLu1-_FV-7bz4cPf18bcHd7GKLDidozBDqtGXLn1gIAClJPZdYAR1RmyUt6p5wD3qMDUdpUXRol3jJf1_qOcTDK0ZkWDyfm0iXRE8WVxrg0fAdx51x3CM-KgFFWfAx7CXM2nOeO-G31XxrbOEUK-v-YKTu37-j0QO7m8l84jf17MpkJTQgIf7Jx_wxDuYL4ZirMcTwQUCHOGAEjzJ4XjZqZpXopKxWGlJYaWhT1ADMcuFtLTQVaGRTrWKVtfJwBgkAMIRKxeimYAMyPZ9zW4YJWq42gPmuUiJTUi84hVKfEq2flZv9AdDzFtPc-gDuA9CU4axi9FzYLzAtHMw0udWHeVNtNg6dkgfeCues_FTYwC4izs4yhUc6HwXui3DZR8q9rkPbyMEzCzsr7izKfY9uACG9tra-FdmO7ER-R7mXseXa2aOr3uafZ7njX1f8x9fdyGlMDAq71ezEGfuB0e5YIdM6SrEytyfIVsf6dObnFNOWqqQeys2MnJaexOM_4vzDC5H3F__n_n8B0&amp;mkt=en-US&amp;hosted=0&amp;device_platform=Windows+10&amp;nca=1&amp;domain_hint=gecopvautaadb2cqvca001.onmicrosoft.com&amp;username=qa3%40globalexcel.com</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forgot your password?</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cta_error_message_text&quot;)/div[@id=&quot;recover_container&quot;]/p[2]/a[@id=&quot;cred_forgot_password_link&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cred_forgot_password_link']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recover_container']/p[2]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Forgot your password?')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('We don', &quot;'&quot;, 't recognize this user ID or password')])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We have a new sign-in experience!'])[1]/following::a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type the email address of the account you want to sign in with.'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in to {0}'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Forgot your password?']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://passwordreset.microsoftonline.com:443/?ru=https%3a%2f%2flogin.microsoftonline.com%2fgecopvautaadb2cqvca001.onmicrosoft.com%2freprocess%3fctx%3drQIIAbWRPYsTURiFMzNJXJeFXRRhsXEFsRCSufMRd40ETDYhJObObDYzCYlscTO5k9xkZm5mcvM1v0C0sdRso5YLKliJP2Gx2FIEGxvFSsRCO5PGehuL9zTvw4Fzzi1BSkrpG-22jGSsoISVwrsJ1QYosbeHQWJ5kt1RbEuy1eDS-tbhq_SLu1-_FV-7bz4cPf18bcHd7GKLDidozBDqtGXLn1gIAClJPZdYAR1RmyUt6p5wD3qMDUdpUXRol3jJf1_qOcTDK0ZkWDyfm0iXRE8WVxrg0fAdx51x3CM-KgFFWfAx7CXM2nOeO-G31XxrbOEUK-v-YKTu37-j0QO7m8l84jf17MpkJTQgIf7Jx_wxDuYL4ZirMcTwQUCHOGAEjzJ4XjZqZpXopKxWGlJYaWhT1ADMcuFtLTQVaGRTrWKVtfJwBgkAMIRKxeimYAMyPZ9zW4YJWq42gPmuUiJTUi84hVKfEq2flZv9AdDzFtPc-gDuA9CU4axi9FzYLzAtHMw0udWHeVNtNg6dkgfeCues_FTYwC4izs4yhUc6HwXui3DZR8q9rkPbyMEzCzsr7izKfY9uACG9tra-FdmO7ER-R7mXseXa2aOr3uafZ7njX1f8x9fdyGlMDAq71ezEGfuB0e5YIdM6SrEytyfIVsf6dObnFNOWqqQeys2MnJaexOM_4vzDC5H3F__n_n8B0&amp;mkt=en-US&amp;hosted=0&amp;device_platform=Windows+10&amp;nca=1&amp;domain_hint=gecopvautaadb2cqvca001.onmicrosoft.com&amp;username=qa3%40globalexcel.com')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/a</value>
   </webElementXpaths>
</WebElementEntity>
